name : Calling Tests

on : [push, pull_request]

jobs:
    run-shell-command: 
      runs-on: macos-latest
      steps: 
      - name: Duration Call Tests
        run : | 
          echo "12 hr call tests action"
          echo "2 hr call tests action"
      - name : Inbound Call Tests
        run :
          echo "Recieve call tests action"
      - name : Testing Shell Command
        run : |
          sysctl -n machdep.cpu.brand_string
      - name: Say Hello World
        run:
          echo "hello world"    

        
      